// <auto-generated />
using System;
using BuildingBlocks.Auditing.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BuildingBlocks.Auditing.Persistence.Migrations
{
    [DbContext(typeof(AuditDbContext))]
    [Migration("20260525172153_AuditInit")]
    partial class AuditInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("audit")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BuildingBlocks.Auditing.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("action");

                    b.Property<string>("BrowserInfo")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("browser_info");

                    b.Property<string>("ClientIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("client_ip");

                    b.Property<string>("ClientName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("client_name");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Exception")
                        .HasColumnType("text")
                        .HasColumnName("exception");

                    b.Property<int>("ExecutionDurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("execution_duration_ms");

                    b.Property<DateTimeOffset>("ExecutionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("execution_time");

                    b.Property<string>("HttpMethod")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("http_method");

                    b.Property<int?>("HttpStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("http_status_code");

                    b.Property<Guid?>("ImpersonatorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("impersonator_user_id");

                    b.Property<string>("MethodName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("method_name");

                    b.Property<string>("Parameters")
                        .HasColumnType("jsonb")
                        .HasColumnName("parameters");

                    b.Property<string>("ReturnValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("return_value");

                    b.Property<string>("ServiceName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("service_name");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Url")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("Action")
                        .HasDatabaseName("ix_audit_logs_action");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_audit_logs_correlation_id");

                    b.HasIndex("ExecutionTime")
                        .HasDatabaseName("ix_audit_logs_execution_time");

                    b.HasIndex("UserId", "ExecutionTime")
                        .HasDatabaseName("ix_audit_logs_user_id_execution_time");

                    b.ToTable("audit_logs", "audit");
                });

            modelBuilder.Entity("BuildingBlocks.Auditing.Entities.EntityChange", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuditLogId")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_log_id");

                    b.Property<DateTimeOffset>("ChangeTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("change_time");

                    b.Property<short>("ChangeType")
                        .HasColumnType("smallint")
                        .HasColumnName("change_type");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("entity_id");

                    b.Property<Guid?>("EntityTenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_tenant_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("entity_type");

                    b.Property<string>("Module")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("module");

                    b.HasKey("Id")
                        .HasName("pk_entity_changes");

                    b.HasIndex("AuditLogId")
                        .HasDatabaseName("ix_entity_changes_audit_log_id");

                    b.HasIndex("ChangeTime")
                        .HasDatabaseName("ix_entity_changes_change_time");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_entity_changes_entity_type_entity_id");

                    b.ToTable("entity_changes", "audit");
                });

            modelBuilder.Entity("BuildingBlocks.Auditing.Entities.EntityPropertyChange", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EntityChangeId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_change_id");

                    b.Property<string>("NewValue")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("new_value");

                    b.Property<string>("OriginalValue")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("original_value");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("property_name");

                    b.Property<string>("PropertyType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("property_type");

                    b.HasKey("Id")
                        .HasName("pk_entity_property_changes");

                    b.HasIndex("EntityChangeId")
                        .HasDatabaseName("ix_entity_property_changes_entity_change_id");

                    b.ToTable("entity_property_changes", "audit");
                });

            modelBuilder.Entity("BuildingBlocks.Auditing.Entities.EntityChange", b =>
                {
                    b.HasOne("BuildingBlocks.Auditing.Entities.AuditLog", null)
                        .WithMany("EntityChanges")
                        .HasForeignKey("AuditLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_entity_changes_audit_logs_audit_log_id");
                });

            modelBuilder.Entity("BuildingBlocks.Auditing.Entities.EntityPropertyChange", b =>
                {
                    b.HasOne("BuildingBlocks.Auditing.Entities.EntityChange", null)
                        .WithMany("PropertyChanges")
                        .HasForeignKey("EntityChangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_entity_property_changes_entity_changes_entity_change_id");
                });

            modelBuilder.Entity("BuildingBlocks.Auditing.Entities.AuditLog", b =>
                {
                    b.Navigation("EntityChanges");
                });

            modelBuilder.Entity("BuildingBlocks.Auditing.Entities.EntityChange", b =>
                {
                    b.Navigation("PropertyChanges");
                });
#pragma warning restore 612, 618
        }
    }
}
