name: Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Restore dependencies
      run: dotnet restore EnterpriseModularMonolith.sln

    - name: Build
      run: dotnet build EnterpriseModularMonolith.sln --no-restore -c Release

    - name: Test with Coverage
      continue-on-error: true
      run: dotnet test EnterpriseModularMonolith.sln --no-build -c Release --verbosity normal --collect:"XPlat Code Coverage"
      
    - name: Generate HTML Report
      run: |
        dotnet tool install -g dotnet-reportgenerator-globaltool
        reportgenerator -reports:"**/TestResults/**/coverage.cobertura.xml" -targetdir:"coveragereport" -reporttypes:"Html"

    - name: Report Coverage
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: coverage-report
        path: |
          **/TestResults/**/coverage.cobertura.xml
          coveragereport/

    - name: Build Docker Image
      run: docker build -t enterprisemodularmonolith/api:latest .
